name: Testing app
on: push
jobs:  
    checkout_and_dependencies:
        runs-on: ubuntu-latest
        steps: 
            # использование готовых actions - чекаут репозитория
            - name: Get the repository code
              uses: actions/checkout@v4
            # использование готовых actions - установка зависимостей
            - name: Install dependencies
              uses: actions/setup-dotnet@v4
    run_tests:
        # ожидание завершения связанной работы
        needs: checkout_and_dependencies
        runs-on: ubuntu-latest
        steps: 
            - name: Get the repository code
              uses: actions/checkout@v4
            - name: Install dependencies for tests
              uses: actions/setup-dotnet@v4
            # запуск тестов 
            - name: Run tests 
              run: dotnet test -v n