name: running_nUnit_tests
on: push
jobs:  
  add_dependencies:
    runs-on: ubuntu-latest
    steps: 
        # использование готовых actions - чекаут репозитория
        - name: Get the repository code
          uses: actions/checkout@v4
        # использование готовых actions - установка зависимостей
        - name: Install dependencies
          uses: actions/setup-dotnet@v4
        # проверка версии dontet
        - name: Checking dotnet version
          run: dotnet --version
